app = "gestion-cuba"
primary_region = "mia"

[build]

[env]
  DATA_DIR = "/data"
  EMAIL_USER = "maykelmillan96@gmail.com"
  EMAIL_PASS = "jjgv kitl piua itox"

[[services]]
  http_checks = []
  internal_port = 3000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "gestioncuba_data"
  destination = "/data"
